# Generated by Django 3.0.5 on 2020-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demande_potentielle_en_2018_par_region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20, unique=True)),
                ('garcon', models.IntegerField(default=0)),
                ('fille', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('poid_de_la_region', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='population_scolarisable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20, unique=True)),
                ('garcon', models.IntegerField(default=0)),
                ('fille', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('pourcent_fille', models.FloatField()),
                ('part_region', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='repartition_du_taux_brute_de_scolarisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20, unique=True)),
                ('garcon', models.FloatField()),
                ('fille', models.FloatField()),
                ('total', models.FloatField()),
                ('Indice_de_parite', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='taux_brute_de_scolarisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20, unique=True)),
                ('garcon', models.FloatField()),
                ('fille', models.FloatField()),
                ('total', models.FloatField()),
                ('poid_de_la_region', models.FloatField()),
            ],
        ),
    ]
