# Generated by Django 2.2 on 2020-04-15 21:03

from django.db import migrations, models, DatabaseError


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elementaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20, unique=True)),
                ('garcon', models.IntegerField(default=0)),
                ('fille', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('poid_region', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='moyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20, unique=True)),
                ('garcon', models.IntegerField(default=0)),
                ('fille', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('pourcent_fille', models.FloatField()),
                ('part_region', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='prescolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20, unique=True)),
                ('garcon', models.IntegerField(default=0)),
                ('fille', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('poid_region', models.FloatField()),
                ('pourcent_fille', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='secondaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20, unique=True)),
                ('garcon', models.IntegerField(default=0)),
                ('fille', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('pourcent_fille', models.FloatField()),
                ('part_region', models.FloatField()),
            ],
        ),
    ]
