# Generated by Django 3.1.dev20200401125511 on 2020-04-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20200421_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux_brut_scolarisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, unique=True)),
                ('garcon', models.FloatField()),
                ('fille', models.FloatField()),
                ('total', models.FloatField()),
                ('indice_de_parite', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('niveau_etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.niveau_etude')),
            ],
        ),
    ]
