# Generated by Django 3.0.5 on 2020-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20200427_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux_brut_scolarisation',
            name='region',
            field=models.CharField(max_length=30),
        ),
    ]
